### ISSUE TITLE
Missing exception handling in general [Bug]

### ISSUE THREAD

**Issue by toredash** [matomo-org/plugin-QueuedTracking#106] opened 2019-05-07 09:43 UTC
The plugin is missing exception handling in general when the Redis backend is used.

There are some issues already that mentions this problem:
#28 
#97 

It would really help if the plugin could report !200 as a HTTP return code if the tracking event was not placed successfully in any queue.

**Comment by tsteur** [comment] 2019-05-07 20:36
Marking this as a duplicate of https://github.com/matomo-org/plugin-QueuedTracking/issues/97 . Not seeing how the other issue be any different. Let me know if there is any difference to it.

**Closed by tsteur** 2019-05-07 20:36 UTC
